blog/urls.py
from django.urls import path

from .views import PostListView, PostDetailView

app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('<int:pk>/', PostDetailView.as_view(), name='post_detail'),
]

qandeel/urls.py
from django.urls import path, re_path

from .views import (
    PoetListView,
    PoetDetailView,
    BookListView,
    BookDetailView,
    SectionListView,
    SectionDetailView,
    CommentCreateView,
    AddToFavoritesView,
    )

app_name = 'qandeel'

urlpatterns = [
    path('poets/', PoetListView.as_view(), name='poet_list'),
    re_path('poets/(?P<slug>[-\w]+)/', PoetDetailView.as_view(), name='poet_detail'),
    path('books/', BookListView.as_view(), name='book_list'),
    re_path('books/(?P<slug>[-\w]+)/', BookDetailView.as_view(), name='book_detail'),
    path('sections/', SectionListView.as_view(), name='section_list'),
    re_path('sections/(?P<slug>[-\w]+)/', SectionDetailView.as_view(), name='section_detail'),
    re_path('comment/(?P<slug>[-\w]+)/', CommentCreateView.as_view(), name='comment_create'),
    path('favorite/<section_slug>/', AddToFavoritesView.as_view(), name='add_to_favorites'),
]

templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block page_title %}{% endblock page_title %}</title>
</head>
<body>
    <a href="{% url "qandeel:poet_list" %}">شائراں</a>
    <a href="{% url "qandeel:book_list" %}">کتاباں</a>
    <a href="{% url "qandeel:section_list" %}">بھراں</a>
    <a href="{% url "blog:post_list" %}">بلاگ</a>
    {% block content %}{% endblock content %}
</body>
</html>

templates/home.html
{% extends "_base.html" %}

{% block page_title %}Home{% endblock page_title %}

{% block content %}
    <h4>Welcome to takband qandeel home page.</h4>
{% endblock content %}