blog/urls.py
from django.urls import path

from .views import PostListView, PostDetailView

app_name = 'blog'

urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('<int:pk>/', PostDetailView.as_view(), name='post_detail'),
]

qandeel/urls.py
from django.urls import path, re_path

from .views import (
    PoetListView,
    PoetDetailView,
    BookListView,
    BookDetailView,
    SectionListView,
    SectionDetailView,
    CommentCreateView,
    AddToFavoritesView,
    )

app_name = 'qandeel'

urlpatterns = [
    path('poets/', PoetListView.as_view(), name='poet_list'),
    re_path('poets/(?P<slug>[-\w]+)/', PoetDetailView.as_view(), name='poet_detail'),
    path('books/', BookListView.as_view(), name='book_list'),
    re_path('books/(?P<slug>[-\w]+)/', BookDetailView.as_view(), name='book_detail'),
    path('sections/', SectionListView.as_view(), name='section_list'),
    re_path('sections/(?P<slug>[-\w]+)/', SectionDetailView.as_view(), name='section_detail'),
    re_path('comment/(?P<slug>[-\w]+)/', CommentCreateView.as_view(), name='comment_create'),
    path('favorite/<section_slug>/', AddToFavoritesView.as_view(), name='add_to_favorites'),
]

qandeel/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from ckeditor.fields import RichTextField

from slugify import slugify
from django_extensions.db.fields import AutoSlugField


def custom_slugify(value):
    return slugify(value, separator='-', allow_unicode=True)


class Century(models.Model):
    name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Centuries'

    def __str__(self):
        return self.name


class Poet(models.Model):
    name = models.CharField(max_length=255)
    slug = AutoSlugField(populate_from=['name'], unique=True, allow_unicode=True, slugify_function=custom_slugify)
    description = RichTextField(verbose_name='Description')
    century = models.ForeignKey(to=Century, related_name='poets',on_delete=models.PROTECT)
    image = models.ImageField(upload_to='poet/poet_image/', blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = custom_slugify(self.name)
        super(Poet, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("qandeel:poet_detail", kwargs={"slug": self.slug})
    
    def __str__(self):
        return self.name


class Book(models.Model):
    name = models.CharField(max_length=255)
    slug = AutoSlugField(populate_from=['name'], unique=True, allow_unicode=True, slugify_function=custom_slugify)
    description = RichTextField()
    poet = models.ForeignKey(to=Poet, related_name='books', on_delete=models.CASCADE)
    cover = models.ImageField(upload_to='book/book_cover/', blank=True, verbose_name='Book Cover')
    
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = custom_slugify(self.name)
        super(Book, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("qandeel:book_detail", kwargs={"slug": self.slug})

    def __str__(self):
        return self.name


class PoeticFormat(models.Model):
    name = models.CharField(max_length=255)

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Topic(models.Model):
    name = models.CharField(max_length=255)

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Section(models.Model):
    title = models.CharField(max_length=255)
    slug = AutoSlugField(populate_from=['title'], unique=True, allow_unicode=True, slugify_function=custom_slugify)
    body = RichTextField()
    book = models.ForeignKey(to=Book, related_name='sections', on_delete=models.CASCADE)
    poetic_format = models.ForeignKey(to=PoeticFormat, related_name='sections', on_delete=models.CASCADE)
    topic = models.ForeignKey(to=Topic, related_name='sections', null=True, blank=True, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = custom_slugify(self.title)
        super(Section, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("qandeel:section_detail", kwargs={"slug": self.slug})

    def __str__(self):
        return self.title
    

class ActiveCommentsManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(active=True, status=Comment.COMMENT_APPROVED)


class Comment(models.Model):
    COMMENT_WAITING = 'wa'
    COMMENT_APPROVED = 'ap'
    COMMENT_NOT_APPROVED = 'na'

    STATUS_CHOICES = [
        (COMMENT_WAITING,'Waiting'),
        (COMMENT_APPROVED,'Approved'),
        (COMMENT_NOT_APPROVED,'Not Approved'),
    ]

    section = models.ForeignKey(to=Section, related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey(to=get_user_model(), related_name='comments', on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    status = models.CharField(max_length=2, choices=STATUS_CHOICES, default=COMMENT_WAITING)
    active = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    modified_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    # Manager
    objects = models.Manager()
    active_comments_manager = ActiveCommentsManager()

    def __str__(self):
        return f'comment {self.id}'


class Favorite(models.Model):
    user = models.ForeignKey(to=get_user_model(), related_name='favorites', on_delete=models.CASCADE)
    section = models.ForeignKey(to=Section, related_name='favorites', on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    modified_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        # Ensure that the same user cannot add the same section to their favorites more than once
        unique_together = ('user', 'section')

    def __str__(self):
        return f'My favorite is: {self.section.title}'

qandeel/forms.py
from django import forms
from django.forms import ModelForm

from .models import Comment, Favorite

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['text',]
        widgets = {
            'text': forms.Textarea(attrs={'rows': 4}),
        }


class AddToFavoritesForm(forms.Form):
    section_slug = forms.CharField(widget=forms.HiddenInput())


class FavoriteForm(ModelForm):
    class Meta:
        model = Favorite
        fields = []

    def __init__(self, *args, **kwargs):
        section_slug = kwargs.pop('section_slug', None)
        super(FavoriteForm, self).__init__(*args, **kwargs)
        if section_slug:
            self.fields['section_slug'] = forms.CharField(widget=forms.HiddenInput(), initial=section_slug)

qandeel/views.py
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.views import generic
from django.shortcuts import redirect
from django.views.generic.edit import FormMixin

from .models import Poet, Book, Section, Comment, Favorite
from .forms import CommentForm


class PoetListView(generic.ListView):
    queryset = Poet.objects.all()
    template_name = 'qandeel/poet_list.html'
    context_object_name = 'poets'
    ordering = 'name'


class PoetDetailView(generic.DetailView):
    model = Poet
    template_name = 'qandeel/poet_detail.html'
    context_object_name = 'poet'

    def get_queryset(self):
        return Poet.objects.all().prefetch_related('books')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        books = self.object.books.all()
        context["books"] = books

        return context
    

class BookListView(generic.ListView):
    queryset = Book.objects.all().select_related('poet')
    template_name = 'qandeel/book_list.html'
    context_object_name = 'books'
    ordering = 'name'


class BookDetailView(generic.DetailView):
    model = Book
    template_name = 'qandeel/book_detail.html'
    context_object_name = 'book'

    def get_queryset(self):
        return Book.objects.all().prefetch_related('sections')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        sections = self.object.sections.all()
        context["sections"] = sections

        return context
    

class SectionListView(generic.ListView):
    queryset = Section.objects.filter(active=True).select_related('poetic_format')
    template_name = 'qandeel/section_list.html'
    context_object_name = 'sections'
    ordering = 'title'


class SectionDetailView(FormMixin, generic.DetailView):
    model = Section
    template_name = 'qandeel/section_detail.html'
    context_object_name = 'section'
    form_class = CommentForm
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        section = self.get_object()
        form = self.get_form()

        is_in_favorites = False
        if self.request.user.is_authenticated:
            is_in_favorites = Favorite.objects.filter(user=self.request.user, section=section).exists()
        
        context["form"] = form
        context["comments"] = Comment.active_comments_manager.select_related('user').filter(section=section)
        context["is_in_favorites"] = is_in_favorites
        
        return context

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        obj.section = self.object
        obj.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('qandeel:section_detail', kwargs={'slug': self.object.slug})


class CommentCreateView(generic.CreateView):
    model = Comment
    form_class = CommentForm

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        section_slug = self.kwargs['slug']
        section = get_object_or_404(Section, slug=section_slug)
        obj.section = section

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('qandeel:section_detail', kwargs={'slug': self.kwargs['slug']})
    

class AddToFavoritesView(generic.CreateView):
    model = Favorite
    template_name = 'qandeel/section_detail.html'

    def post(self, request, *args, **kwargs):
        section_slug = self.kwargs['section_slug']
        section = get_object_or_404(Section, slug=section_slug)
        user = request.user

        is_in_favorites = Favorite.objects.filter(user=user, section=section).exists()

        if is_in_favorites:
            Favorite.objects.filter(user=user, section=section).delete()
        else:
            Favorite.objects.create(user=user, section=section)

        return redirect('qandeel:section_detail', slug=section_slug)

qandeel/templates/qandeel/book_detail.html
{% extends "_base.html" %}

{% block page_title %}{{book.name}}{% endblock page_title %}

{% block content %}
    <h1>Book Name: {{book.name}}</h1>
    <h3>Book Author: {{book.poet}}</h3>
    <p>
        {{book.description|safe}}
    </p>

    <h1>Sections:</h1>

    <ul>
        {% for section in sections %}
            <li>
                <a href="{{ section.get_absolute_url }}">{{section.title}}</a>
            </li>
            {% empty %}
            <p>No sections.</p>
        {% endfor %}
    </ul>
{% endblock content %}

qandeel/templates/qandeel/book_list.html
{% extends "_base.html" %}

{% block page_title %}Books{% endblock page_title %}

{% block content %}
    {% for book in books %}
        <h1>{{book.name}}</h1>
        <h3>{{book.poet}}</h3>
        <a href="{{book.get_absolute_url}}">more...</a>
        {% endfor %}

{% endblock content %}

qandeel/templates/qandeel/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    Takband Qandeel
</body>
</html>

qandeel/templates/qandeel/poet_detail.html
{% extends "_base.html" %}

{% block page_title %}{{poet.name}}{% endblock page_title %}

{% block content %}
    <h1>Name: {{poet.name}}</h1>
    <p>Description: {{poet.description|safe}}</p>
    <h6>Year: {{poet.century}}</h6>
    
    <h2>Books:</h2>
    <ul>
      {% for book in books %}
        <li><a href="{{ book.get_absolute_url }}">{{ book.name }}</a></li>
      {% empty %}
        <li>books not found.</li>
      {% endfor %}
    </ul>
{% endblock content %}

qandeel/templates/qandeel/poet_list.html
{% extends "_base.html" %}

{% block page_title %}Poets{% endblock page_title %}

{% block content %}
    {% for poet in poets %}
        <h1>{{poet.name}}</h1>
        <a href="{{poet.get_absolute_url}}">more...</a>
        ===
    {% endfor %}

{% endblock content %}

qandeel/templates/qandeel/section_detail.html
{% extends "_base.html" %}

{% block page_title %}{{section.title}}{% endblock page_title %}

{% block content %}
    <h1>{{section.title}}</h1>
    <h3>{{section.body|safe}}</h3>

    {% if user.is_authenticated %}
      {% if is_in_favorites %}
        <p>This section is already in your favorites.</p>
        <form method="post" action="{% url 'qandeel:add_to_favorites' section.slug %}">
            {% csrf_token %}
            <button type="submit">Remove from Favorites</button>
        </form>
      {% else %}
          <form method="post" action="{% url 'qandeel:add_to_favorites' section.slug %}">
              {% csrf_token %}
              <button type="submit">Add to Favorites</button>
          </form>
      {% endif %}
    {% else %}
      <p><a href="{% url 'account_login' %}">Log in</a> to add this section to your favorites.</p>
    {% endif %}

    <form method="post" action="{% url 'qandeel:comment_create' slug=section.slug %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit Comment</button>
    </form>

    <h2>Comments:</h2>
    <ul>
      {% for comment in comments %}
        <li>
            {{comment.user}} says: {{comment.text}}
        </li>
      {% empty %}
        <li>comments not found.</li>
      {% endfor %}
    </ul>
{% endblock content %}

qandeel/templates/qandeel/section_list.html
{% extends "_base.html" %}

{% block page_title %}Sections{% endblock page_title %}

{% block content %}
    {% for secction in sections %}
        <h1>{{secction.title}}</h1>
        <h3>{{secction.poetic_format}}</h3>
        <a href="{{secction.get_absolute_url}}">more...</a>
        ===
    {% endfor %}

{% endblock %}